name: Check_Practic01 pipeline
on:
  #push:
  #  branches:
  #    - main
  #    - contact
  workflow_dispatch:

jobs:
  checking-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v3
        with:
          ref: practic

      #- name: Check Java
      #  run: 'java -version'

      #- name: Directory
      #  run: 'pwd'

      #- name: List root files
      #  run: 'ls -al /root/'

