name: Check Practic11 pipeline
on:
  #push:
  #  branches:
  #    - main
  #    - contact
  workflow_dispatch:

jobs:
  checking-pipeline:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read

      #container:
        #image: ghcr.io/softservedata/devopsjen:main
        #ports:
        #  - 8080:8080
        #options: --rm --detach

      steps:
        - uses: docker-practice/actions-setup-docker@master
          timeout-minutes: 12

        - name: Check Docker
          run: 'docker version'

        - name: Setup container
          run: 'docker run --detach --name jenkins_server -p 8080:8080 ghcr.io/softservedata/devopsjen:main'

        - name: Checkout the repo
          uses: actions/checkout@v3
          with:
            ref: practic

        - name: Install Java 11
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '11'

        - name: Check Java
          run: 'java -version'

        - name: Directory
          run: 'pwd'

        - name: List root files
          run: 'ls -al /root/'

        - name: Download Jenkins CLI
          run: 'wget http://localhost:8080/jnlpJars/jenkins-cli.jar'

        - name: List files
          run: 'ls -al'

        #- uses: jenkinsci/jfr-setup-action@master
        #- uses: jenkinsci/jfr-runtime-action@master
        #  with:
        #    command: run
        #    jenkinsfile: Jenkinsfile
