name: Check Practic1 pipeline. Run Jenkinsfile
on:
  # Triggers the workflow on push or pull request
  #push:
  #  branches:
  #    - main
  #    - contact
  #pull_request:
  #  branches: [ "main" ]
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  checking-pipeline:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      steps:
        - name: Checks-out your repository
          uses: actions/checkout@v3
          with:
            ref: practic

      - uses: jenkinsci/jfr-setup-action@master

      - uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile




        #- name: Install Java 11
        #  uses: actions/setup-java@v3
        #  with:
        #    distribution: 'zulu'
        #    java-version: '11'

        - name: Check Java
          run: 'java -version'

        - name: Directory
          run: 'pwd'

        - name: List root files
          run: 'ls -al /root/'
