name: Check Practic1 pipeline
on:
  #push:
  #  branches:
  #    - main
  #    - contact
  workflow_dispatch:

jobs:
  checking-pipeline:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read

      container:
        image: ghcr.io/softservedata/devopsjen:main
        #ports:
        #  - 8080

      steps:
        - name: Checkout the repo
          uses: actions/checkout@v3
          with:
            ref: practic

      #  - name: Install Java 11
      #    uses: actions/setup-java@v3
      #    with:
      #      distribution: 'zulu'
      #      java-version: '11'

        #- name: Download Plugins
        #  run: 'java -jar jenkins-plugin-manager-2.12.11.jar --war jenkins.war --plugin-file plugins.txt --plugin-download-directory data/.jenkins/plugins'

        #- name: Check Images
        #  run: 'docker images'

        #- name: Check Containers
        #  run: 'docker ps -a'

        - name: Check Java
          run: 'java -version'

        - name: List files
          run: 'ls -al'
