name: Check Practic11 pipeline
on:
  #push:
  #  branches:
  #    - main
  #    - contact
  workflow_dispatch:

jobs:
  checking-pipeline:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read

      steps:
        - name: Checks-out your repository
          uses: actions/checkout@v3
          with:
            ref: practic

      - name: Setup jenkinsci
        uses: jenkinsci/jfr-setup-action@master

      - name: Running Jenkinsfile
        uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
