name: Publish Docker image
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read

      steps:
        - name: Checkout the repo
          uses: actions/checkout@v3

        - name: Install Java 11
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '11'

        - name: Download Plugins
          run: 'java -jar jenkins-plugin-manager-2.12.11.jar --war jenkins.war --plugin-file plugins.txt --plugin-download-directory data/.jenkins/plugins'

        - name: Login to GitHub Container Registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
